# Generated by Django 5.0.6 on 2024-06-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_rename_destination_destinosturisticos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinosturisticos',
            name='estadoDestino',
            field=models.BooleanField(default=True),
        ),
    ]
