# Generated by Django 5.0.6 on 2024-06-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_destinosturisticos_estadodestino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinosturisticos',
            name='estadoDestino',
        ),
    ]
